Fix 1 issue
DmitryDoskolovich/Test-task-React pull request #3
Opened 2019-09-30 17:40 UTC by DmitryDoskolovich

fix #1

2019-10-01 08:09 UTC, akuznetsov-md commented
Все-таки ветки следует называть по смыслу. Исходя из того, какие изменения там находятся.

2019-10-01 08:31 UTC, akuznetsov-md requested changes

2019-10-01 08:31 UTC, akuznetsov-md commented on src/components/LoginForm/LoginForm.js
> +        className="login-form app__login-form_position app__login-form_size"
Если я правильно понял, `app__login-form_position` и `app__login-form_size` это классы-модификаторы некоторого блока `app`. Т.е. это какой-то контекст использования компонента login-form. В компонентах не должно быть явного указания, где и как он будет использоваться, т.к. теряется универсальность и изолированность.

2019-10-01 08:31 UTC, akuznetsov-md commented on src/components/LoginForm/LoginForm.js
>              <p className="login-form__avatar-name">{this.state.avatarName}</p>
Нейминг очень важная шутка. Как бы ты описал, что находится на этом экране человеку, который его не видит?

![image](https://user-images.githubusercontent.com/35480039/65946445-3389f180-e447-11e9-923c-e2c1243805fe.png)

2019-10-01 10:40 UTC, DmitryDoskolovich commented on src/components/LoginForm/LoginForm.js
> +        className="login-form app__login-form_position app__login-form_size"
Да, все так. Как я понял по БЭМ нужно задавать внешнюю геометрию и позиционирование через родителя, т.е. в компоненте указываются модификаторы, а описываются в css родителя (https://ru.bem.info/methodology/quick-start/#%D0%BC%D0%B8%D0%BA%D1%81) или правильно будет передавать внешнюю геометрию и позиционирование через props, т.е. блок app будет передавать нужные классы для позиционирования и внешней геометрии?

2019-10-01 10:52 UTC, akuznetsov-md commented on src/components/LoginForm/LoginForm.js
> +        className="login-form app__login-form_position app__login-form_size"
> т.е. блок app будет передавать нужные классы для позиционирования и внешней геометрии

Да, именно так.

2019-10-01 11:02 UTC, DmitryDoskolovich commented on src/components/LoginForm/LoginForm.js
>              <p className="login-form__avatar-name">{this.state.avatarName}</p>
Согласен, что нейминг это важно. Я бы описал так "Форма авторизованного пользователя с аватаром, именем и кнопкой выхода."

2019-10-01 11:31 UTC, akuznetsov-md commented on src/components/LoginForm/LoginForm.js
>              <p className="login-form__avatar-name">{this.state.avatarName}</p>
А почему форма? Мы тут разве заполняем какие-то данные? Имя кого? Судя по твоему коду это имя аватара :)

2019-10-01 12:33 UTC, DmitryDoskolovich commented on src/components/LoginForm/LoginForm.js
>              <p className="login-form__avatar-name">{this.state.avatarName}</p>
Тогда можно перефразировать, что окно авторизованного пользователя с аватаром пользователя, именем пользователя и кнопкой выхода. Нужно это окошко выделить в отдельный компонент получается?

2019-10-01 12:53 UTC, DmitryDoskolovich commented on src/components/LoginForm/LoginForm.js
>              <p className="login-form__avatar-name">{this.state.avatarName}</p>
Насчет компонента я наверное загнул. Текущий компонент должен рисовать либо форму, либо div с аватаркой, именем и кнопкой.

2019-10-01 13:52 UTC, akuznetsov-md commented on src/components/LoginForm/LoginForm.js
>              <p className="login-form__avatar-name">{this.state.avatarName}</p>
Я все-таки разделил бы форму и профиль пользователя на разные компоненты. Они вполне могут существовать независимо друг от друга.

2019-10-01 13:52 UTC, akuznetsov-md commented on src/components/LoginForm/LoginForm.js
>              <p className="login-form__avatar-name">{this.state.avatarName}</p>
Но изначальный комментарий был про выбор названия `login-form__avatar-name`

2019-10-01 14:59 UTC, DmitryDoskolovich commented on src/components/LoginForm/LoginForm.js
> +        className="login-form app__login-form_position app__login-form_size"
Спасибо.
В коммите (https://github.com/DmitryDoskolovich/Test-task-React/pull/3/commits/e1ad69bf038adfd5585b2598dbcc4f95c4afff0e) внес изменения для компонентов LoginForm и Logo (в Logo была такая же ошибка)

2019-10-01 20:14 UTC, akuznetsov-md commented on src/App.js
> +      <div className="authorization-page authorization-page_default page__authorization-page_position page__authorization-page_size ">
Не очень понимаю, зачем для определения стиля страницы использовать 4 класса.

2019-10-01 21:08 UTC, DmitryDoskolovich commented on src/components/LoginForm/LoginForm.js
>              <p className="login-form__avatar-name">{this.state.avatarName}</p>
Понял, спасибо, буду работать над неймингом)
(18d91e7) добавил новый компонент UserProfie

2019-10-01 21:25 UTC, DmitryDoskolovich commented on src/App.js
> +      <div className="authorization-page authorization-page_default page__authorization-page_position page__authorization-page_size ">
Наверное можно ограничиться authorization-page и page__authorization-page_position-size
Стоит ли разделять модификаторы влияющие на размер и на позиционирование? В примерах из документации БЭМ есть отдельные модификаторы для размера блока и для его позиционирования

2019-10-02 06:24 UTC, akuznetsov-md commented on src/App.js
> +    };
В state имеет смысл хранить данные которые будут меняться и влиять на рендер. Это явно не тот случай

2019-10-02 06:25 UTC, akuznetsov-md commented on src/App.js
> +      <div className="authorization-page authorization-page_default page__authorization-page_position page__authorization-page_size ">
А какую задачу решает модификатор `page__authorization-page_position-size`?

2019-10-02 08:58 UTC, DmitryDoskolovich commented on src/App.js
> +      <div className="authorization-page authorization-page_default page__authorization-page_position page__authorization-page_size ">
Задает позиционирование и размер блока App, у App родитель body, поэтому прописал через родителя.
Наверное это не правильно. App описывает страницу и достаточно будет описать authorization-page с размерами и позиционированием

2019-10-02 20:22 UTC, DmitryDoskolovich commented on src/App.js
> +      <div className="authorization-page authorization-page_default page__authorization-page_position page__authorization-page_size ">
Исправил в коммите 
090e0e5

2019-10-02 20:23 UTC, DmitryDoskolovich commented on src/App.js
> +    };
Понял, спасибо.
Внес изменения в коммите 
090e0e5
использовал defaultProps, такое решение корректное?

2019-10-06 21:59 UTC, DmitryDoskolovich commented
@akuznetsov-md 
Удалил лишние bind из конструктора LoginForm и функцию handleSumbit сделал стрелочной функцией, подумал, что так код чище будет
9d81d20

2019-10-07 09:18 UTC, akuznetsov-md requested changes

2019-10-07 09:18 UTC, akuznetsov-md commented on src/App.js
> +    };
Само по себе defaultProps рабочее решение. Но конкретно в твоем случае ты используешь их необоснованно. 

Props - это какие-то _переменные_ параметры компонента. Props - это параметры, которые можно задавать компоненту извне. Разве есть необходимость в процессе работы приложения изменять классы classLoginForm, classLogo, classUserProfile?

2019-10-07 09:18 UTC, akuznetsov-md commented on src/components/LoginForm/LoginForm.js
> +        className={`login-form ${this.props.className}`}
Для комбинации классов можно пользоваться удобной библиотекой https://www.npmjs.com/package/classnames. Есть вероятность, что this.props.className будет не задан. В таком случае набор классов будет "login-form undefined"

2019-10-08 13:10 UTC, DmitryDoskolovich commented on src/components/LoginForm/LoginForm.js
> +        className={`login-form ${this.props.className}`}
Спасибо, библиотеку добавил. Библиотека решает проблему с "login-form undefined".

defaultProps переписал на const. Если есть вероятность, что не надо будет задавать внешнюю геометрию и позиционирование, то придется писать const CLASSLOGO="", иначе будет ошибка "is not defined", либо убирать className из <Logo />, не знаю насколько этот вариант подходит, с использованием props такой проблемы не было

ac24540

2019-10-08 14:21 UTC, akuznetsov-md commented on src/App.js
> +            className="app__user-profile_size app__user-profile_position"
Похожую проблему обсуждали здесь https://github.com/DmitryDoskolovich/Test-task-React/pull/3#discussion_r330753035

2019-10-08 16:05 UTC, DmitryDoskolovich commented on src/App.js
> +            className="app__user-profile_size app__user-profile_position"
Поправил.
Получилось, что app__login-form и app__user-profile практически одинаковые, я немного изменил компонент UserProfile и в App.css сделал общий класс app__window_properties

4feeecd

2019-10-09 06:48 UTC, akuznetsov-md requested changes

2019-10-09 06:48 UTC, akuznetsov-md commented on src/App.js
> +    this.setState({ userName: responseObj["name"] });
Три вызова setState можно объединить в один. Каждый вызов setState, грубо говоря, запускает механизм вычисления изменений Virtual DOM.

2019-10-09 06:48 UTC, akuznetsov-md commented on src/App.js
> +    this.handleOnClickLogout = this.handleOnClickLogout.bind(this);
loginSuccessful и handleOnClickLogout являются стрелочными функциями, и не имеют собственного контекста (this). Это означает что this внутри этих функций всегда будет ссылкой на экземпляр класса App. Т.е. this всегда будет "правильным" для нас.

Поэтому явно bind-ить контекст не имеет смысла

2019-10-09 06:48 UTC, akuznetsov-md commented on src/App.js
> +      </div>
Не помню писал это уже или нет. Компонент = Блок из БЭМ. Если корректно разбить интерфейс на компоненты по БЭМ, то перейти к компонентном подходу на React не составит труда.

С т.з. БЭМ попробуй описать этот компонент — и, соответственно, попробуй найти в чем ошибка

2019-10-09 14:08 UTC, DmitryDoskolovich commented on src/App.js
> +      </div>
Как я понял проблема была в именах классов.
Переименовал на app, app__logo, app__content.
Появилось несколько вопросов:
1) Стоит ли переименовать App во что-то более осмысленное, например Page и вынести в отдельную папку (к другим компонентам), или и так все понятно?
2) Можно вместо передачи className в дочерние компоненты сделать конструкцию вида:
<div className="app__logo">
	<Logo />
</div>
Есть ли в этом смысл?

2019-10-09 14:28 UTC, akuznetsov-md commented on src/App.js
> +      </div>
>Переименовал на app, app__logo, app__content.

Да, верно

>Стоит ли переименовать App во что-то более осмысленное, например Page и вынести в отдельную папку (к другим компонентам), или и так все понятно?

App — нормально. У приложения должна быть некоторая входная точка и логично назвать эту точку App. Page это все-таки часть приложения, так что это не лучший вариант.

> Можно вместо передачи className в дочерние компоненты сделать конструкцию вида

Можно, но неэффективно. В реальных приложениях такая вложенность приведет к большому количеству лишних оберток. Чем больше DOM-узлов, тем больше ресурсов будет тратить браузер на их обработку. Соответственно, есть риск в потере производительности

2019-10-09 14:34 UTC, akuznetsov-md commented
Этот PR стоит вмержить, т.к. до некоторой точки он уже дошел. Код выглядит гораздо лучше. Но с декомпозицией еще не все хорошо. У тебя есть дублирование кода. Посмотри, что еще стоит вынести в отдельные компоненты, чтобы избавиться от такого дублирование и оформи правки в виде нового PR

2019-10-09 15:11 UTC, merged